package io.radanalytics.tutorial.drools.rules;

import io.radanalytics.tutorial.drools.rule.model.Input;
import io.radanalytics.tutorial.drools.rule.model.Output;


rule "Value Michael is Valid"
    when
        $input : Input( val == "Michael" )
    then
        modify( $input ) {
        	setValid( true )	
        };
end

rule "Value Billy is valid"
    when
        $input : Input( val == "Billy" )
    then
        modify( $input ) {
        	setValid( true )	
        };
end

rule "Value Matt is valid"
    when
        $input : Input( val == "Matt" )
    then
        modify( $input ) {
        	setValid( true )	
        };
end

rule "Value Kevin is valid"
    when
        $input : Input( val == "Kevin" )
    then
        modify( $input ) {
        	setValid( true )	
        };
end

rule "Value Eddie is valid"
    when
        $input : Input( val == "Eddie" )
    then
        modify( $input ) {
        	setValid( true )	
        };
end